const fs = require('fs');

// We will parse constants.ts and generate the pristine, professional version
const file = 'src/lib/constants.ts';
let content = fs.readFileSync(file, 'utf8');

// Replacement dictionary for distorted titles
const nameReplacements = [
  { raw: "Inspired by L@tt@fa Kh@mrah Waha Perfume", clean: "Inspired by Lattafa Khamrah Qahwa", type: "Inspired", gender: "Unisex", scent: "Sweet & Spicy", notes: { top: "Cinnamon, Cardamom, Ginger", heart: "Praline, Candied Fruits, White Flowers", base: "Coffee, Vanilla, Tonka Bean, Benzoin, Oud" } },
  { raw: "Inspired By CR 7 ( Worn By Cristi@no Ron@ld0 )", clean: "Inspired by Cristiano Ronaldo CR7", type: "Inspired", gender: "Men", scent: "Fresh & Aromatic", notes: { top: "Bergamot, Artemisia, Cardamom, Lavender", heart: "Cinnamon, Cedar, Iris, Tobacco", base: "Sandalwood, Amber, Vanilla, Musk" } },
  { raw: "Inspired by Miss D Perfume", clean: "Inspired by Miss Dior", type: "Inspired", gender: "Women", scent: "Floral & Fresh", notes: { top: "Lily of the Valley, Peony, Iris", heart: "Centifolia Rose, Apricot, Peach", base: "Vanilla, Tonka Bean, White Musk, Sandalwood" } },
  { raw: "Inspired by P@co Rabbane Lady Milli0n Perfume", clean: "Inspired by Paco Rabanne Lady Million", type: "Inspired", gender: "Women", scent: "Sweet & Floral", notes: { top: "Bitter Orange, Raspberry, Neroli", heart: "Orange Blossom, Arabian Jasmine, Gardenia", base: "Patchouli, Honey, Amber" } },
  { raw: "Inspired By Ġůccï FL0r@ Gorgeous Magnolia", clean: "Inspired by Gucci Flora Gorgeous Magnolia", type: "Inspired", gender: "Women", scent: "Floral & Fruity", notes: { top: "Dewberry, Coconut Accord, Sweet Orange", heart: "Magnolia Essence, Jasmine Sambac, Clary Sage", base: "Patchouli, Blonde Woods, Coconut Musk" } },
  { raw: "Inspired by YSL Libre", clean: "Inspired by YSL Libre", type: "Inspired", gender: "Women", scent: "Floral & Lavender", notes: { top: "Lavender, Mandarin Orange, Blackcurrant, Petitgrain", heart: "Lavender, Orange Blossom, Jasmine Sambac", base: "Madagascar Vanilla, Cedar, Ambergris, Musk" } },
  { raw: "Inspired By Gucci Flora Gorgeous Jasmine", clean: "Inspired by Gucci Flora Gorgeous Jasmine", type: "Inspired", gender: "Women", scent: "Floral & Radiant", notes: { top: "Mandarin Essence, Bergamot, Black Pepper", heart: "Grandiflorum Jasmine, Magnolia, Damask Rose", base: "Sandalwood, Benzoin, Patchouli" } },
  { raw: "Inspired By Gucci Flora Gorgeous Orchid", clean: "Inspired by Gucci Flora Gorgeous Orchid", type: "Inspired", gender: "Women", scent: "Sweet Gourmand Floral", notes: { top: "Vanilla Infusion, Dewy Greens", heart: "Vanilla Orchid, White Lily", base: "Ozonic Notes, Tonka Bean, Soft Musk" } },
  { raw: "Celestial Perfume Imagination", clean: "Inspired by Louis Vuitton Imagination", type: "Inspired", gender: "Men", scent: "Fresh Citrus & Tea", notes: { top: "Calabrian Bergamot, Citron, Sicilian Orange", heart: "Tunisian Neroli, Nigerian Ginger, Ceylon Cinnamon", base: "Chinese Black Tea, Ambroxan, Guaiac Wood, Olibanum" } },
  { raw: "Celestial Perfume J'@dore", clean: "Inspired by Dior J'adore", type: "Inspired", gender: "Women", scent: "Floral Bouquet", notes: { top: "Pear, Melon, Magnolia, Peach, Mandarin", heart: "Jasmine, Lily-of-the-Valley, Tuberose, Freesia, Rose", base: "Musk, Vanilla, Cedar, Blackberry" } },
  { raw: "Celestial Perfume Wisal Dahab", clean: "Inspired by Ajmal Wisal Dhahab", type: "Inspired", gender: "Unisex", scent: "Oud & Floral", notes: { top: "Pear, Apple, Peach, Grapefruit, Mandarin", heart: "Rose, Jasmine, Orchid, Geranium", base: "Sandalwood, Cedarwood, White Musk, Patchouli" } },
  { raw: "Celestial Perfume Khamrah", clean: "Inspired by Lattafa Khamrah", type: "Inspired", gender: "Unisex", scent: "Warm Gourmand & Amber", notes: { top: "Cinnamon, Nutmeg, Bergamot", heart: "Dates, Praline, Tuberose, Mahonial", base: "Vanilla, Tonka Bean, Benzoin, Myrrh, Akigalawood" } },
  { raw: "Celestial Perfume Tabacco VN", clean: "Inspired by Tom Ford Tobacco Vanille", type: "Inspired", gender: "Unisex", scent: "Warm Spicy & Vanilla", notes: { top: "Tobacco Leaf, Spicy Notes", heart: "Tonka Bean, Tobacco Blossom, Vanilla, Cacao", base: "Dry Fruit Accord, Rich Woody Notes" } },
  { raw: "Celestial Perfume Bacc@rat R", clean: "Inspired by Baccarat Rouge 540", type: "Inspired", gender: "Unisex", scent: "Amber & Saffron", notes: { top: "Saffron, Jasmine", heart: "Amberwood, Ambergris", base: "Fir Resin, Cedarwood" } },
  { raw: "Celestial Perfume Black Opium", clean: "Inspired by YSL Black Opium", type: "Inspired", gender: "Women", scent: "Warm Coffee & Vanilla", notes: { top: "Pear, Pink Pepper, Orange Blossom", heart: "Coffee, Jasmine, Bitter Almond, Licorice", base: "Vanilla, Patchouli, Cashmere Wood, Cedar" } },
  { raw: "Celestial Perfume Cool Water", clean: "Inspired by Davidoff Cool Water", type: "Inspired", gender: "Men", scent: "Fresh Aquatic", notes: { top: "Sea Water, Mint, Green Notes, Lavender, Coriander", heart: "Sandalwood, Jasmine, Neroli, Geranium", base: "Musk, Oakmoss, Cedar, Tobacco, Amber" } },
  { raw: "Celestial Perfume Avnts", clean: "Inspired by Creed Aventus", type: "Inspired", gender: "Men", scent: "Fruity Chypre & Smoke", notes: { top: "Pineapple, Bergamot, Blackcurrant, Apple", heart: "Birch, Patchouli, Moroccan Jasmine, Rose", base: "Musk, Oakmoss, Ambergris, Vanille" } },
  { raw: "Celestial Perfume DTD", clean: "Inspired by Diptyque Tam Dao", type: "Inspired", gender: "Unisex", scent: "Woody Sandalwood", notes: { top: "Italian Cypress, Myrtle, Rose", heart: "Sandalwood, Cedarwood", base: "Brazilian Rosewood, Spices, Amber, White Musk" } },
  { raw: "Celestial Perfume Guilty", clean: "Inspired by Gucci Guilty Pour Homme", type: "Inspired", gender: "Men", scent: "Woody Aromatic", notes: { top: "Lavender, Amalfi Lemon", heart: "African Orange Flower, Neroli", base: "Virginia Cedar, Patchouli, Vanilla" } },
  { raw: "Celestial Perfume Ombre Leather", clean: "Inspired by Tom Ford Ombré Leather", type: "Inspired", gender: "Unisex", scent: "Rich Leather & Spice", notes: { top: "Cardamom", heart: "Leather, Jasmine Sambac", base: "Amber, Moss, Patchouli" } },
  { raw: "Celestial Perfume Ck1", clean: "Inspired by Calvin Klein CK One", type: "Inspired", gender: "Unisex", scent: "Fresh Citrus Clean", notes: { top: "Lemon, Green Notes, Bergamot, Pineapple, Mandarin", heart: "Lily-of-the-Valley, Jasmine, Violet, Nutmeg, Rose", base: "Green Tea Accord, Musk, Cedar, Sandalwood, Amber" } },
  { raw: "Celestial Perfume Bombshell", clean: "Inspired by Victoria's Secret Bombshell", type: "Inspired", gender: "Women", scent: "Fruity Floral", notes: { top: "Passionfruit, Grapefruit, Pineapple, Tangerine, Strawberry", heart: "Peony, Vanilla Orchid, Red Berries, Jasmine, Lily-of-the-Valley", base: "Musk, Woody Notes, Oakmoss" } },
  { raw: "Celestial Perfume Eros", clean: "Inspired by Versace Eros", type: "Inspired", gender: "Men", scent: "Fresh Mint & Vanilla", notes: { top: "Mint, Green Apple, Italian Lemon", heart: "Tonka Bean, Ambroxan, Geranium", base: "Madagascar Vanilla, Virginian Cedar, Atlas Cedar, Vetiver, Oakmoss" } },
  { raw: "Celestial Perfume Oud Wood", clean: "Inspired by Tom Ford Oud Wood", type: "Inspired", gender: "Unisex", scent: "Precious Oud & Rosewood", notes: { top: "Rosewood, Cardamom, Chinese Pepper", heart: "Oud Wood, Sandalwood, Vetiver", base: "Tonka Bean, Vanilla, Amber" } },
  { raw: "Celestial Perfume Paradoxe", clean: "Inspired by Prada Paradoxe", type: "Inspired", gender: "Women", scent: "Floral Amber", notes: { top: "Pear, Tangerine, Calabrian Bergamot", heart: "Orange Blossom, Neroli Essence, Jasmine Sambac", base: "Bourbon Vanilla, Amber, White Musk, Benzoin" } },
  { raw: "Celestial Perfume My way", clean: "Inspired by Giorgio Armani My Way", type: "Inspired", gender: "Women", scent: "White Floral & Citrus", notes: { top: "Orange Blossom, Bergamot", heart: "Tuberose, Indian Jasmine", base: "Madagascar Vanilla, White Musk, Virginian Cedar" } },
  { raw: "Celestial Perfume Eden Apple", clean: "Inspired by Kayali Eden Juicy Apple 01", type: "Inspired", gender: "Women", scent: "Juicy Fruity Apple", notes: { top: "Red Apple, Lychee, Blackcurrant, Pink Grapefruit", heart: "Wild Berries, Raspberry Blossom, Jasmine", base: "Sugar, Vanilla, Amber, Musk" } },
  { raw: "Celestial Perfume Coco M", clean: "Inspired by Chanel Coco Mademoiselle", type: "Inspired", gender: "Women", scent: "Oriental Fresh Floral", notes: { top: "Orange, Mandarin Orange, Bergamot, Orange Blossom", heart: "Turkish Rose, Jasmine, Mimosa, Ylang-Ylang", base: "Patchouli, White Musk, Vanilla, Vetiver, Tonka Bean, Opoponax" } },
  { raw: "Celestial Perfume O'Blossom", clean: "Inspired by Jo Malone Orange Blossom", type: "Inspired", gender: "Unisex", scent: "Fresh Blossom & Citrus", notes: { top: "Tangerine Blossom, Clementine, Green Notes", heart: "Orange Blossom, Lotus, Lilac", base: "Lilac, Orris Wood, Vetiver" } },
  { raw: "Celestial Perfume K Vanilla", clean: "Inspired by Kayali Vanilla 28", type: "Inspired", gender: "Women", scent: "Rich Warm Vanilla", notes: { top: "Vanilla Orchid, Creamy Jasmine", heart: "Brown Sugar, Tonka Bean", base: "Amber, Musk, Amberwood, Patchouli" } },
  { raw: "Celestial Perfume Si", clean: "Inspired by Giorgio Armani Sì", type: "Inspired", gender: "Women", scent: "Fruity Chypre & Cassis", notes: { top: "Cassis (Blackcurrant Nectar)", heart: "May Rose, Freesia", base: "Vanilla, Patchouli, Woody Notes, Ambroxan" } },
  { raw: "Celestial Perfume H-GG", clean: "Inspired by Carolina Herrera Good Girl", type: "Inspired", gender: "Women", scent: "Sensual Tuberose & Cocoa", notes: { top: "Almond, Coffee, Bergamot, Lemon", heart: "Tuberose, Jasmine Sambac, Orange Blossom, Orris", base: "Tonka Bean, Cacao, Vanilla, Praline, Sandalwood, Musk, Amber" } },
  { raw: "Celestial Perfume Bloom", clean: "Inspired by Gucci Bloom", type: "Inspired", gender: "Women", scent: "White Floral Garden", notes: { top: "Green Notes, Orange", heart: "Natural Tuberose, Jasmine Sambac, Rangoon Creeper", base: "Vanilla, Sandalwood, Orris Root" } },
  { raw: "Celestial Perfume N-5", clean: "Inspired by Chanel No. 5", type: "Inspired", gender: "Women", scent: "Classic Aldehydic Floral", notes: { top: "Aldehydes, Ylang-Ylang, Neroli, Bergamot, Lemon", heart: "Iris, Jasmine, Rose, Orris Root, Lily-of-the-Valley", base: "Civet, Musk, Amber, Sandalwood, Moss, Vanilla, Vetiver, Patchouli" } },
  { raw: "Celestial Perfume Bright Crystal", clean: "Inspired by Versace Bright Crystal", type: "Inspired", gender: "Women", scent: "Fresh Floral Pomegranate", notes: { top: "Yuzu, Pomegranate, Ice Accord", heart: "Peony, Lotus, Magnolia", base: "Musk, Mahogany, Amber" } },
  { raw: "Celestial Perfume Flora", clean: "Inspired by Gucci Flora", type: "Inspired", gender: "Women", scent: "Elegant Citrus Floral", notes: { top: "Peony, Citruses, Mandarin Orange", heart: "Osmanthus, Rose", base: "Sandalwood, Patchouli, Pink Pepper" } },
  { raw: "Inspired By C@lvin Klein 0bsessi0n ( Worn By Salman Khan )", clean: "Inspired by Calvin Klein Obsession (Worn by Salman Khan)", type: "Inspired", gender: "Men", scent: "Warm Amber & Spices", notes: { top: "Cinnamon, Lavender, Coriander, Mandarin, Lime, Bergamot", heart: "Myrrh, Nutmeg, Carnation, Brazilian Rosewood, Pine, Sage", base: "Amber, Vanilla, Sandalwood, Musk, Patchouli, Vetiver" } },
  { raw: "Inspired by Jo M@lone 0range Bl0ssom (Worn by Deepika P@duk0ne)", clean: "Inspired by Jo Malone Orange Blossom (Worn by Deepika Padukone)", type: "Inspired", gender: "Women", scent: "Fresh Orange Blossom", notes: { top: "Tangerine Blossom, Clementine, Green Leaves", heart: "Orange Blossom, Lotus, Water Lily", base: "Lilac, Orris Root, Vetiver" } },
  { raw: "Inspired By Pr@da P@rad0xe", clean: "Inspired by Prada Paradoxe", type: "Inspired", gender: "Women", scent: "Amber & Neroli", notes: { top: "Pear, Tangerine, Bergamot", heart: "Orange Blossom, Neroli Essence, Jasmine Sambac", base: "Bourbon Vanilla, Amber, White Musk, Benzoin" } },
  { raw: "Inspired By My W@y Gi0rgi0 Arm@ni", clean: "Inspired by Giorgio Armani My Way", type: "Inspired", gender: "Women", scent: "Bright Tuberose & Bergamot", notes: { top: "Orange Blossom, Bergamot", heart: "Tuberose, Indian Jasmine", base: "Madagascar Vanilla, White Musk, Cedar" } },
  { raw: "Inspired By LV Im@gin@tions", clean: "Inspired by Louis Vuitton Imagination", type: "Inspired", gender: "Men", scent: "Citrus & Black Tea", notes: { top: "Calabrian Bergamot, Citron, Sicilian Orange", heart: "Tunisian Neroli, Nigerian Ginger, Cinnamon", base: "Chinese Black Tea, Ambroxan, Guaiac Wood" } },
  { raw: "Inspired By K@y@li Eden Juicy Apple", clean: "Inspired by Kayali Eden Juicy Apple 01", type: "Inspired", gender: "Women", scent: "Crisp Red Apple", notes: { top: "Red Apple, Lychee, Blackcurrant", heart: "Wild Berries, Raspberry Blossom, Jasmine", base: "Vanilla, Sugar, Amber, Musk" } },
  { raw: "Inspired By K@yali V@nilla", clean: "Inspired by Kayali Vanilla 28", type: "Inspired", gender: "Women", scent: "Warm Brown Sugar & Vanilla", notes: { top: "Vanilla Orchid, Jasmine", heart: "Brown Sugar, Tonka Bean", base: "Amber, Musk, Amberwood, Patchouli" } },
  { raw: "Inspired By Gi0rgi0 Arm@ni Si", clean: "Inspired by Giorgio Armani Sì", type: "Inspired", gender: "Women", scent: "Blackcurrant & Rose", notes: { top: "Cassis", heart: "May Rose, Freesia", base: "Vanilla, Patchouli, Ambroxan, Wood Notes" } },
  { raw: "Inspired By D J'@dore Perfume", clean: "Inspired by Dior J'adore", type: "Inspired", gender: "Women", scent: "Floral Elegance", notes: { top: "Pear, Melon, Magnolia, Peach, Mandarin", heart: "Jasmine, Lily-of-the-Valley, Tuberose, Freesia", base: "Musk, Vanilla, Cedar, Blackberry" } },
  { raw: "Inspired By Vers@ce Dyl@n Blue Perfume", clean: "Inspired by Versace Dylan Blue", type: "Inspired", gender: "Men", scent: "Fresh Aquatic & Incense", notes: { top: "Calabrian Bergamot, Water Notes, Grapefruit, Fig Leaf", heart: "Ambroxan, Black Pepper, Patchouli, Violet Leaf, Papyrus", base: "Incense, Musk, Tonka Bean, Saffron" } },
  { raw: "Inspired By @jm@l Wis@l Dh@h@b Perfume", clean: "Inspired by Ajmal Wisal Dhahab", type: "Inspired", gender: "Unisex", scent: "Gilded Oud & Rose", notes: { top: "Pear, Apple, Peach, Grapefruit, Mandarin", heart: "Rose, Jasmine, Orchid, Geranium", base: "Sandalwood, Cedarwood, White Musk, Patchouli" } },
  { raw: "Inspired By L@tt@fa Kh@mrah Perfume", clean: "Inspired by Lattafa Khamrah", type: "Inspired", gender: "Unisex", scent: "Cinnamon & Dates Gourmand", notes: { top: "Cinnamon, Nutmeg, Bergamot", heart: "Dates, Praline, Tuberose, Mahonial", base: "Vanilla, Tonka Bean, Benzoin, Myrrh, Akigalawood" } },
  { raw: "Inspired By R@s@si H@wµs P0µr H0mu Perfume", clean: "Inspired by Rasasi Hawas for Him", type: "Inspired", gender: "Men", scent: "Aquatic Fruity Plum", notes: { top: "Apple, Bergamot, Lemon, Cinnamon", heart: "Watery Notes, Plum, Orange Blossom, Cardamon", base: "Ambergris, Musk, Driftwood, Patchouli" } },
  { raw: "Inspired by Čh@nÈl N0.5 Perfume ( Worn by S@ra ali Kh@n )", clean: "Inspired by Chanel No. 5 (Worn by Sara Ali Khan)", type: "Inspired", gender: "Women", scent: "Iconic Powdery Floral", notes: { top: "Aldehydes, Ylang-Ylang, Neroli, Bergamot, Lemon", heart: "Iris, Jasmine, Rose, Orris Root, Lily-of-the-Valley", base: "Civet, Amber, Sandalwood, Musk, Moss, Vanilla, Patchouli" } },
  { raw: "Inspired By Roja Ely$ium Perfume (Worn By H@rdik P@ndya)", clean: "Inspired by Roja Elysium (Worn by Hardik Pandya)", type: "Inspired", gender: "Men", scent: "Ultra Fresh Citrus & Vetiver", notes: { top: "Grapefruit, Lemon, Bergamot, Lime, Thyme, Artemisia, Galbanum", heart: "Vetiver, Juniper Berries, Blackcurrant, Apple, Pink Pepper, Cedar", base: "Ambergris, Leather, Benzoin, Labdanum, Vanilla" } },
  { raw: "Inspired By JPG Ultra M@le Perfume", clean: "Inspired by Jean Paul Gaultier Ultra Male", type: "Inspired", gender: "Men", scent: "Sweet Pear & Vanilla", notes: { top: "Pear, Lavender, Mint, Bergamot, Lemon", heart: "Cinnamon, Clary Sage, Caraway", base: "Black Vanilla Husk, Amber, Cedar, Patchouli" } },
  { raw: "Inspired By Ombre Nom@de Perfume", clean: "Inspired by Louis Vuitton Ombre Nomade", type: "Inspired", gender: "Unisex", scent: "Smoky Oud & Incense", notes: { top: "Raspberry, Saffron", heart: "Rose, Geranium, Birch", base: "Agarwood (Oud), Incense, Benzoin, Amberwood" } },
  { raw: "Inspired by T0mford T@abacc0 V@nille Perfume", clean: "Inspired by Tom Ford Tobacco Vanille", type: "Inspired", gender: "Unisex", scent: "Spicy Tobacco & Creamy Vanilla", notes: { top: "Tobacco Leaf, Spicy Notes", heart: "Tonka Bean, Tobacco Blossom, Vanilla, Cacao", base: "Dry Fruit Accord, Woody Notes" } },
  { raw: "Inspired by Ch@nel @llure H0mme Spt Perfume ( Worn by S@if Al! Kh@n  )", clean: "Inspired by Chanel Allure Homme Sport (Worn by Saif Ali Khan)", type: "Inspired", gender: "Men", scent: "Crisp Citrus & White Musk", notes: { top: "Orange, Sea Notes, Aldehydes, Blood Mandarin", heart: "Pepper, Neroli, Cedar", base: "Tonka Bean, Vanilla, White Musk, Amber, Vetiver, Elemi Resin" } },
  { raw: "Inspired By B@ccarat R0uge 540 Perfume", clean: "Inspired by Baccarat Rouge 540", type: "Inspired", gender: "Unisex", scent: "Airy Amber & Saffron", notes: { top: "Bitter Almond, Saffron", heart: "Egyptian Jasmine, Cedarwood", base: "Ambergris, Woody Musk" } },
  { raw: "Inspired By YSL Black 0pium Perfume", clean: "Inspired by YSL Black Opium", type: "Inspired", gender: "Women", scent: "Dark Coffee & Sweet Vanilla", notes: { top: "Pear, Pink Pepper, Orange Blossom", heart: "Coffee, Jasmine, Bitter Almond, Licorice", base: "Vanilla, Patchouli, Cedar, Cashmere Wood" } },
  { raw: "Inspired Ch@nel Coco M@demoiselle Perfume ( Worn by Ileana D'Cruz )", clean: "Inspired by Chanel Coco Mademoiselle (Worn by Ileana D'Cruz)", type: "Inspired", gender: "Women", scent: "Vibrant Citrus Patchouli", notes: { top: "Orange, Mandarin Orange, Bergamot, Orange Blossom", heart: "Turkish Rose, Jasmine, Mimosa, Ylang-Ylang", base: "Patchouli, White Musk, Vanilla, Vetiver, Tonka Bean" } },
  { raw: "Inspired By Gucci Blo0m Perfume ( Worn by Aditi Rao Hydari )", clean: "Inspired by Gucci Bloom (Worn by Aditi Rao Hydari)", type: "Inspired", gender: "Women", scent: "Natural White Tuberose", notes: { top: "Green Accord, Orange", heart: "Tuberose, Jasmine Sambac, Rangoon Creeper", base: "Vanilla, Sandalwood, Orris Root" } },
  { raw: "King Of Bollywood Perfume ( Inspired By T@MD@0 & DUNHILL ICON) Pack Of Two Perfumes", clean: "King of Bollywood Duo (Inspired by Diptyque Tam Dao & Dunhill Icon)", type: "Inspired", gender: "Men", scent: "Noble Sandalwood & Neroli", notes: { top: "Italian Cypress, Neroli, Italian Bergamot", heart: "Sandalwood, Black Pepper, Cardamom, Lavender", base: "Smoky Oud, Vetiver, Leather, Oakmoss" } },
  { raw: "Inspired By Carolina Herrera Go0d Girl Perfume", clean: "Inspired by Carolina Herrera Good Girl", type: "Inspired", gender: "Women", scent: "Bold Cocoa & Tuberose", notes: { top: "Almond, Coffee, Bergamot, Lemon", heart: "Tuberose, Jasmine Sambac, Orange Blossom", base: "Tonka Bean, Cacao, Vanilla, Praline, Sandalwood" } },
  { raw: "Inspired by Tomford ombre Le@ther Perfume ( Worn by Arjun Kap0or ) Unisex", clean: "Inspired by Tom Ford Ombré Leather (Worn by Arjun Kapoor)", type: "Inspired", gender: "Unisex", scent: "Spiced Floral Leather", notes: { top: "Cardamom", heart: "Leather, Jasmine Sambac", base: "Amber, Moss, Patchouli" } },
  { raw: "Inspired by Paco Rabbane one Milli0n Perfume ( Worn by Ed Sheer@n )", clean: "Inspired by Paco Rabanne 1 Million (Worn by Ed Sheeran)", type: "Inspired", gender: "Men", scent: "Cinnamon, Leather & Amber", notes: { top: "Blood Mandarin, Grapefruit, Mint", heart: "Cinnamon, Spicy Notes, Rose", base: "Amber, Leather, Woody Notes, Indian Patchouli" } },
  { raw: "Inspired by DUNHILL IC0N Perfume", clean: "Inspired by Dunhill Icon", type: "Inspired", gender: "Men", scent: "Aromatic Woody Neroli", notes: { top: "Neroli, Italian Bergamot, Black Pepper, Petitgrain", heart: "Black Pepper, Cardamom, Sage, Provence Lavender, Juniper Berries", base: "Vetiver, Agarwood (Oud), Leather, Oakmoss, Iris" } },
  { raw: "Inspired by Creed Av3ntus Perfume ( Worn By D@vid Beckh@m ) Unisex", clean: "Inspired by Creed Aventus (Worn by David Beckham)", type: "Inspired", gender: "Unisex", scent: "Smoky Pineapple & Birch", notes: { top: "Bergamot, Blackcurrant, Apple, Pineapple", heart: "Birch, Juniper Berries, Patchouli, Moroccan Jasmine", base: "Musk, Oakmoss, Ambergris, Vanilla" } },
  { raw: "Inspired by Victoria Secret B0mbshell Perfume", clean: "Inspired by Victoria's Secret Bombshell", type: "Inspired", gender: "Women", scent: "Bright Passionfruit & Peony", notes: { top: "Passionfruit, Grapefruit, Pineapple, Tangerine, Strawberry", heart: "Peony, Vanilla Orchid, Red Berries, Jasmine, Lily-of-the-Valley", base: "Musk, Woody Notes, Oakmoss" } },
  { raw: "Inspired by Tam Da0 Perfume", clean: "Inspired by Diptyque Tam Dao", type: "Inspired", gender: "Unisex", scent: "Creamy Sacred Sandalwood", notes: { top: "Italian Cypress, Myrtle, Rose", heart: "Sandalwood, Cedarwood", base: "Brazilian Rosewood, Spices, Amber, White Musk" } },
  { raw: "Inspired by Versace Er0s Perfume", clean: "Inspired by Versace Eros", type: "Inspired", gender: "Men", scent: "Vibrant Mint & Cedar", notes: { top: "Mint, Green Apple, Lemon", heart: "Tonka Bean, Ambroxan, Geranium", base: "Madagascar Vanilla, Virginian Cedar, Atlas Cedar, Vetiver, Oakmoss" } },
  { raw: "Inspired by D 0ff Cool W@ter Perfume ( Worn by Aksh@y Kum@r ) Unisex", clean: "Inspired by Davidoff Cool Water (Worn by Akshay Kumar)", type: "Inspired", gender: "Unisex", scent: "Crisp Ocean Mint", notes: { top: "Sea Water, Mint, Green Notes, Lavender, Coriander", heart: "Sandalwood, Jasmine, Neroli, Geranium", base: "Musk, Oakmoss, Cedar, Tobacco, Amber" } },
  { raw: "Inspired By Viking Perfume ( Worn by Vir@t K0hli )", clean: "Inspired by Creed Viking (Worn by Virat Kohli)", type: "Inspired", gender: "Men", scent: "Fiery Pink Pepper & Peppermint", notes: { top: "Pink Pepper, Spicy Mint, Bergamot, Lemon, Absinthe, Orange", heart: "Lavender, Bulgarian Rose, Clove, Allspice, Orris Root, Jasmine", base: "Vetiver, Cedar, White Musk, Tonka Bean" } },
  { raw: "Inspired By Azzaro The Most W@nted Perfume", clean: "Inspired by Azzaro The Most Wanted", type: "Inspired", gender: "Men", scent: "Warm Toffee & Cardamom", notes: { top: "Cardamom, Mandarin", heart: "Toffee, Caramel Accord, Lavender", base: "Amberwood, Bourbon Vanilla, Vetiver" } },
  { raw: "Inspired By Ck 0ne Perfume", clean: "Inspired by Calvin Klein CK One", type: "Inspired", gender: "Unisex", scent: "Clean Bergamot & Green Tea", notes: { top: "Lemon, Green Notes, Bergamot, Pineapple, Mandarin Orange, Cardamom", heart: "Lily-of-the-Valley, Jasmine, Violet, Nutmeg, Rose, Orris Root", base: "Green Accord, Musk, Cedar, Sandalwood, Oakmoss, Green Tea, Amber" } },
  { raw: "Inspired By D Homme P@rfum Perfume", clean: "Inspired by Dior Homme Parfum", type: "Inspired", gender: "Men", scent: "Powdery Iris & Dark Leather", notes: { top: "Tuscan Iris, Italian Orange", heart: "Leather, Rose", base: "Sandalwood, Agarwood (Oud), Ambrette, Cedar" } },
  { raw: "Inspired By Gucci Gµilty Perfume ( Worn by R@nveer Singh ) Unisex", clean: "Inspired by Gucci Guilty (Worn by Ranveer Singh)", type: "Inspired", gender: "Unisex", scent: "Aromatic Lavender & Patchouli", notes: { top: "Lavender, Amalfi Lemon", heart: "African Orange Flower, Neroli", base: "Virginia Cedar, Patchouli, Vanilla" } },
  { raw: "Inspired by Terre De Herme$ Perfume ( Worn by Sanj@y Dutt )", clean: "Inspired by Terre d'Hermès (Worn by Sanjay Dutt)", type: "Inspired", gender: "Men", scent: "Earthy Orange, Flint & Vetiver", notes: { top: "Orange, Grapefruit", heart: "Pepper, Pelargonium, Flint Accord", base: "Vetiver, Cedar, Patchouli, Benzoin" } },
  { raw: "Inspired by Tomford oud W00d Perfume ( Worn by Moni R0y & Am@n Gupta Bo@t ) Unisex", clean: "Inspired by Tom Ford Oud Wood (Worn by Mouni Roy & Aman Gupta)", type: "Inspired", gender: "Unisex", scent: "Smoky Exotic Oud & Cardamom", notes: { top: "Rosewood, Cardamom, Chinese Pepper", heart: "Oud Wood, Sandalwood, Vetiver", base: "Tonka Bean, Vanilla, Amber" } },
  { raw: "Inspired By Bvlgari Men In Bl@ck Perfume", clean: "Inspired by Bvlgari Man In Black", type: "Inspired", gender: "Men", scent: "Warm Rum, Leather & Spices", notes: { top: "Spices, Rum, Tobacco", heart: "Leather, Iris, Tuberose", base: "Tonka Bean, Guaiac Wood, Benzoin" } },
  { raw: "Inspired by Creed Green Irish Twe3d Perfume ( Worn by S@hid Kapoor )", clean: "Inspired by Creed Green Irish Tweed (Worn by Shahid Kapoor)", type: "Inspired", gender: "Men", scent: "Fresh Green Verbena & Iris", notes: { top: "Lemon Verbena, Iris", heart: "Violet Leaves", base: "Ambergris, Sandalwood" } },
  { raw: "Inspired By Ġůccï FL0r@ Perfume ( Worn by Alia Bh@tt )", clean: "Inspired by Gucci Flora (Worn by Alia Bhatt)", type: "Inspired", gender: "Women", scent: "Delicate Peony & Osmanthus", notes: { top: "Peony, Citruses, Mandarin Orange", heart: "Osmanthus, Rose", base: "Sandalwood, Patchouli, Pink Pepper" } },
  { raw: "Inspired By Bleu De Ch@nel Perfume ( Worn by Adity@ Roy K@p00r )", clean: "Inspired by Bleu de Chanel (Worn by Aditya Roy Kapur)", type: "Inspired", gender: "Men", scent: "Fresh Citrus, Mint & Cedarwood", notes: { top: "Grapefruit, Lemon, Mint, Pink Pepper", heart: "Ginger, Nutmeg, Jasmine, Iso E Super", base: "Incense, Vetiver, Cedar, Sandalwood, Patchouli, Labdanum, White Musk" } },
  { raw: "Inspired By Armani C0de Perfume", clean: "Inspired by Giorgio Armani Armani Code", type: "Inspired", gender: "Men", scent: "Seductive Tonka & Leather", notes: { top: "Lemon, Bergamot", heart: "Star Anise, Olive Blossom, Guaiac Wood", base: "Leather, Tonka Bean, Tobacco" } },
  { raw: "Inspired by Versace Bright Cryst@l Perfume ( Worn by Kiara Advani & Manushi Chhillar )", clean: "Inspired by Versace Bright Crystal (Worn by Kiara Advani)", type: "Inspired", gender: "Women", scent: "Luminous Yuzu & Lotus", notes: { top: "Yuzu, Pomegranate, Ice Accord", heart: "Peony, Lotus, Magnolia", base: "Musk, Mahogany, Amber" } },
  { raw: "Inspired By Acqua Di Gio Pr0fumo Perfume", clean: "Inspired by Giorgio Armani Acqua Di Giò Profumo", type: "Inspired", gender: "Men", scent: "Deep Marine & Incense", notes: { top: "Sea Notes, Bergamot", heart: "Rosemary, Sage, Geranium", base: "Incense, Patchouli" } },
  { raw: "Inspired by D S@uv@ge Perfume ( Worn by J0hnny depp )", clean: "Inspired by Dior Sauvage (Worn by Johnny Depp)", type: "Inspired", gender: "Men", scent: "Crisp Bergamot, Pepper & Ambroxan", notes: { top: "Calabrian Bergamot, Pepper", heart: "Sichuan Pepper, Lavender, Pink Pepper, Vetiver, Patchouli, Geranium, Elemi", base: "Ambroxan, Cedar, Labdanum" } }
];

console.log('Total replacement entries configured:', nameReplacements.length);

// Apply each replacement to content
nameReplacements.forEach(({ raw, clean, notes }) => {
  if (content.includes(raw)) {
    content = content.replaceAll(raw, clean);
    console.log('Replaced:', raw, '->', clean);
  }
});

// Update FLEUR and ESSPRIVE mentions in constants.ts
content = content.replaceAll("ESSPRIVE", "RK Perfume");
content = content.replaceAll("FLEUR / ESSPRIVE · RK Perfume", "RK Perfume");
content = content.replaceAll("FLEUR", "RK Perfume");

fs.writeFileSync(file, content, 'utf8');
console.log('Updated constants.ts successfully');
